### ISSUE TITLE
[InvalidOperationException: The same key was already used for another template!]

### ISSUE THREAD

**Issue by imran1231** [Antaris/RazorEngine#226] opened 2015-01-29 14:06 UTC
I am using,

`Engine.Razor.RunCompile(template, "pop", products.GetType(), products);`

```
[InvalidOperationException: The same key was already used for another template!]
   RazorEngine.Templating.<>c__DisplayClass1.<AddDynamic>b__0(ITemplateKey k, ITemplateSource oldSource) +91
   System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory) +71
   RazorEngine.Templating.DelegateTemplateManager.AddDynamic(ITemplateKey key, ITemplateSource source) +85
   RazorEngine.Templating.RazorEngineService.AddTemplate(ITemplateKey key, ITemplateSource templateSource) +27
   RazorEngine.Templating.DynamicWrapperService.AddTemplate(ITemplateKey key, ITemplateSource templateSource) +14
   RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String templateSource, String name, Type modelType, Object model, DynamicViewBag viewBag) +58
```

**Comment by matthid** [comment] 2015-01-29 14:09
As the exception says: You already the key "pop" for another template. I close this as this looks like expected behavior. If you can show a testcase when this happens on the first call I will re-open this.

**Closed by matthid** 2015-01-29 14:09 UTC

**Comment by imran1231** [comment] 2015-01-29 14:12
You mean for each template I should have different name. What about,

Engine.Razor.RunCompile(template, template, products.GetType(), products);

**Comment by imran1231** [comment] 2015-01-29 14:25
OK I did with MD5,
```
    Engine.Razor.RunCompile(template, GetMd5Hash(template), products.GetType(), products);



       private static string GetMd5Hash(string input)
        {
            var md5 = MD5.Create();
            var inputBytes = System.Text.Encoding.ASCII.GetBytes(input);
            var hash = md5.ComputeHash(inputBytes);
            var sb = new StringBuilder();
            foreach (byte t in hash)
            {
                sb.Append(t.ToString("X2"));
            }
            return sb.ToString();
        }
```

**Comment by matthid** [comment] 2015-01-29 14:40
Basically the idea is that this key is used for caching purposes, so it doesn't make sense to re-use it for multiple templates.
The other thing is that the API is designed in a way so that you don't need to provide the template source code at all: http://antaris.github.io/RazorEngine/#Set-a-template-manager
If you provide a template manager you can just write
```csharp
Engine.Razor.RunCompile("home.cshtml", products.GetType(), products);
```

**Comment by mikemuggli** [comment] 2015-03-09 23:04
I have the same sort of issue going on here. I think the underlying problem is that it isn't invalidating and updating the cache when a template changes. 

For example, say I am reading a .cshtml file from disk as my template and then I make a change to that file. I would expect that RazorEngine would update its cache with my new file, but instead it throws "The same key was already used for another template!" exception.

**Comment by matthid** [comment] 2015-03-09 23:11
Please also follow the discussion on https://github.com/Antaris/RazorEngine/issues/232

**Comment by chris03** [comment] 2016-03-21 19:13
I'm a bit confused about this and the doc isn't really clear...

My use-case :
- A web app that sends emails. The template for the email is editable and stored in the database.

So I'm expecting RazorEngine to do this simple task: 
Combine the template with some data into a string that I can email.

Now, from what I understand (because I got the exception from this issue), it's not as simple as I would have expected. RazorEngine's API forces me away from my simple use-case into using a template manager and caching stuff. It would be nice to document more the reason behind why this is necessary. What I found out here (correct me if wrong) and isn't well documented on the website:

- When a template is compiled, the associated memory cannot be freed.
(Because assemblies can't be unloaded)
- Since creating a new templates has a memory cost that can't be freed, it's kind of a memory leak and therefore it must be done as few times as possible ? (and that's why there's all that Caching/Template management stuff).

So based on these facts, what would be a the best approach for a web app that has several templates that can change during runtime ?

As suggested by imran1231, I could generate a md5/sha1 of the template and use it as a key ?
That would ensure that the cached template is reused until it changes. Hopefully the template doesn't change very often which will limit memory usage. Or is there a better way ?

And, as per recommendation from #232, what would be the benefit of implementing a custom manager/caching/invalidating if the memory associated with an old template cannot be released ?

**Comment by leedavi** [comment] 2016-12-07 02:21
I find this a major problem with RazorEngine, the situation for dynamic templates is a real use case.  And some kind of option to replace the cached template or to remove it should be implemented without having to create a caching provider.

I understand your point that caching should not be replaced once implemented, but in the real world this is driving my designers crazy,  they have to restart the app pool after every design change.  Looks like the MD5 workaround is the only easy option for now!

**Comment by matthid** [comment] 2016-12-07 06:30
I really don't know what else I could write (see #232)

**Comment by leedavi** [comment] 2016-12-07 07:05
Yes, I posted on that thread as well :-)

It's a shame you can't find a work around for this.  I'm no expert in this area so I'll bow to your judgement, but I do think it's holding the project back.  I've implemented the MD5 workaround and that seems to work well, but it's not very elegant.

Maybe a option on the config to allow this kind of multiple temnplatekey might be a solution, after all in most use case the templates will not be changed.  It's just a major problem in development more than anything!

I do like this project, but I just don;t have the time to get deep into this kind of complexity, but the MD5 workaround solves my problem for now.

Thx for you work on this.

**Comment by simoazzo** [comment] 2017-01-18 09:48
I agree with @leedavi 

I have as well used the MD5 workaround, and again, it solves my problem for now.

Are there are future updates regarding this fix please?

Thanks

**Comment by mstrojek** [comment] 2017-02-16 14:46
My solution (don't now where i got it from) is to disable the temp file locking:

add this before your compile command:
`
var config = new TemplateServiceConfiguration();

config.Language = Language.CSharp;

config.EncodedStringFactory = new HtmlEncodedStringFactory();

config.DisableTempFileLocking = true; // this seems to be the relevant part

var service = RazorEngineService.Create(config);

Engine.Razor = service;
`

**Comment by vk927** [comment] 2017-07-05 19:59
@mstrojek @imran1231 @leedavi 
as per the mstrojek, I changed the configs . and I got this message
`C:\Users[user_account]\AppData\Local\Temp\RazorEngine_qeouaznq. ett' manually!`

Now when want to revert back i.e to the task automatically, `config.DisableTempFileLocking = true`;  is not working

**Comment by mrameezraja** [comment] 2017-09-09 15:38
This is working fine for me.
```c#
string templateContent = "Hey, i am content";
string razorTemplateName = "emailTemplate";
bool isTemplateCached = Engine.Razor.IsTemplateCached(razorTemplateName, null);

if (!isTemplateCached)
{
      var layoutSource = new LoadedTemplateSource(templateContent);
      Engine.Razor.AddTemplate(razorTemplateName, layoutSource);
      Engine.Razor.RunCompile(templateContent, (razorTemplateName), null, (object)_model);
}
else
{
      Engine.Razor.Run(razorTemplateName, null, (object)_model);
}
```
