### ISSUE TITLE
Incompatibility with ASP.Net Core

### ISSUE THREAD

**Issue by davidchoo12** [Antaris/RazorEngine#365] opened 2016-02-28 17:25 UTC
![image](https://cloud.githubusercontent.com/assets/7817101/13380668/32c2deba-de83-11e5-80ac-153cec4f0e43.png)

Is there any plans for RazorEngine to support ASP.Net Core?

**Comment by matthid** [comment] 2016-03-01 17:59
Duplicate of https://github.com/Antaris/RazorEngine/issues/322

**Closed by matthid** 2016-03-01 17:59 UTC
