### ISSUE TITLE
Method not found: 'Void Microsoft.AspNet.Razor.Parser.ParserContext.OnError(Microsoft.AspNet.Razor.SourceLocation, System.String)'.

### ISSUE THREAD

**Issue by skorunka** [Antaris/RazorEngine#369] opened 2016-03-08 13:44 UTC
Empty "Class Library (Package)" project.
+ "Microsoft.AspNet.Mvc": "6.0.0-rc1-final"
+ "RazorEngine": "4.2.7-beta1"

**View**
```
@model Ui.Web.ViewModel
Name = @Model.Name
```

**ViewModel**
```
namespace Ui.Web
{
	public class ViewModel
	{
		public string Name { get; set; }
	}
}
 
```
**Code**
`Engine.Razor.RunCompile("....", "Key", typeof(ViewModel), new ViewModel { Name = "Hi" });`

**Runtime error:**

```
Exception thrown: 'System.MissingMethodException' in Microsoft.AspNet.Razor.dll
Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request
System.MissingMethodException: Method not found: 'Void Microsoft.AspNet.Razor.Parser.ParserContext.OnError(Microsoft.AspNet.Razor.SourceLocation, System.String)'.
   at RazorEngine.Compilation.CSharp.CSharpCodeParser.ModelDirective()
   at Microsoft.AspNet.Razor.Parser.CSharpCodeParser.AfterTransition()
   at Microsoft.AspNet.Razor.Parser.CSharpCodeParser.AtTransition(CSharpSymbol current)
   at Microsoft.AspNet.Razor.Parser.CSharpCodeParser.ParseBlock()
   at Microsoft.AspNet.Razor.Parser.HtmlMarkupParser.OtherParserBlock()
   at Microsoft.AspNet.Razor.Parser.HtmlMarkupParser.SkipToAndParseCode(Func`2 condition)
   at Microsoft.AspNet.Razor.Parser.HtmlMarkupParser.SkipToAndParseCode(HtmlSymbolType type)
   at Microsoft.AspNet.Razor.Parser.HtmlMarkupParser.ParseDocument()
   at Microsoft.AspNet.Razor.Parser.RazorParser.ParseCore(ITextDocument input)
   at Microsoft.AspNet.Razor.Parser.RazorParser.Parse(ITextDocument input)
   at Microsoft.AspNet.Razor.RazorTemplateEngine.GenerateCodeCore(ITextDocument input, String className, String rootNamespace, String sourceFileName, String checksum, Nullable`1 cancelToken)
   at Microsoft.AspNet.Razor.RazorTemplateEngine.GenerateCode(TextReader input, String className, String rootNamespace, String sourceFileName, Nullable`1 cancelToken)
   at Microsoft.AspNet.Razor.RazorTemplateEngine.GenerateCode(TextReader input, String className, String rootNamespace, String sourceFileName)
   at RazorEngine.Compilation.CompilerServiceBase.GetGeneratorResult(RazorEngineHost host, TypeContext context)
   at RazorEngine.Compilation.CompilerServiceBase.GetCodeCompileUnit(TypeContext context)
   at RazorEngine.Compilation.DirectCompilerServiceBase.Compile(TypeContext context)
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileTypeImpl(TypeContext context)
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType_Windows(TypeContext context)
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType(TypeContext context)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
   at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String templateSource, String name, Type modelType, Object model, DynamicViewBag viewBag)
```

**Comment by senj** [comment] 2016-03-17 08:24
I'm having the same problem...

**Comment by KonKras** [comment] 2016-03-24 13:46
Same issue for me.

**Comment by matthid** [comment] 2016-04-03 10:46
Duplicate of https://github.com/Antaris/RazorEngine/issues/322

**Comment by bragma** [comment] 2016-05-11 10:12
@matthid I'm not sure I can help, but maybe some direction on how to proceed could help me if I want to try something on spare time that may end up in a PR... :)

**Comment by campersau** [comment] 2016-07-17 12:24
This should be fixed with https://github.com/Antaris/RazorEngine/pull/402 in RazorEngine 4.4.0-rc1
>    Context.OnError now takes an additional length argument

**Comment by matthid** [comment] 2016-07-17 12:26
Thanks @campersau. @skorunka please try latest and open a new issue if there are still problems.

**Closed by matthid** 2016-07-17 12:26 UTC
Labels: feature-request, up-for-grabs
