### ISSUE TITLE
RazorEngine crashes when compiling template

### ISSUE THREAD

**Issue by PhilipDaniels** [Antaris/RazorEngine#218] opened 2015-01-23 14:35 UTC
I am trying to compile a template with a model in a static site generator I am writing (early days yet). The code is on Github. To reproduce, follow these instructions

git clone https://github.com/PhilipDaniels/Lithogen
git checkout a1f3cefa8f6c06d12fad1ad095caddd327286c48   # Version known to fail
Then open a command prompt and run install_npm_modules.cmd
Open Lithogen.sln in Visual Studio, and Build Lithogen.TaskShim and Lithogen.
Rebuild Lithogen.Boilerplate (it will error out). This causes the shim to write Lithogen.xml and Lithogen.json, which Lithogen.exe needs. In the Lithogen.Boilerplate\Lithogen\Tools\Lithogen folder you will find Lithogen.exe. In that same folder will be Lithogen.log which will contain this stack trace.

Stick a breakpoint in RazorProcessor.Process() in Lithogen.Core.
Set the startup project to Lithogen.
Now you can debug in the normal way.

2015-01-23 12:59:35.87 [         0.93] ViewDirectoryProcessor: processing C:\Users\pdaniels\repos\Lithogen\src\Lithogen.Boilerplate\Views\solarsystem.cshtml.
2015-01-23 12:59:35.87 [  0.01,  0.93] RazorProcessor: compiling C:\Users\pdaniels\repos\Lithogen\src\Lithogen.Boilerplate\Views\solarsystem.cshtml.
2015-01-23 12:59:35.91 [  0.04,  0.97] RazorEngineReferenceResolver: Attempting to get references.
2015-01-23 12:59:35.92 [  0.01,  0.98] RazorEngineReferenceResolver: Returning C:\Users\pdaniels\repos\Lithogen\src\Lithogen.Boilerplate\bin\Lithogen.Boilerplate.dll.
2015-01-23 12:59:35.92 [         0.98] RazorEngineReferenceResolver: Returning C:\Users\pdaniels\repos\Lithogen\src\Lithogen.Boilerplate\bin\Newtonsoft.Json.dll.
2015-01-23 12:59:35.92 [         0.99] RazorEngineReferenceResolver: Returning C:\Users\pdaniels\repos\Lithogen\src\Lithogen.Boilerplate\bin\System.Net.Http.Formatting.dll.
2015-01-23 12:59:35.93 [         0.99] RazorEngineReferenceResolver: Returning C:\Users\pdaniels\repos\Lithogen\src\Lithogen.Boilerplate\bin\System.Web.Http.dll.
2015-01-23 12:59:36.09 [  0.16,  1.15] System.NullReferenceException: Object reference not set to an instance of an object.
   at RazorEngine.Templating.CompiledTemplate.get_TemplateAssembly()
   at RazorEngine.Templating.DefaultCachingProvider.<>c__DisplayClass5.<CacheTemplateHelper>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at RazorEngine.Templating.DefaultCachingProvider.CacheTemplateHelper(ICompiledTemplate template, ITemplateKey templateKey, Type modelTypeKey)
   at RazorEngine.Templating.DefaultCachingProvider.CacheTemplate(ICompiledTemplate template, ITemplateKey templateKey)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String templateSource, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at Lithogen.Core.Implementations.RazorProcessor.Process(String filename, String contents) in c:\Users\pdaniels\repos\Lithogen\src\Lithogen.Core\Implementations\RazorProcessor.cs:line 39
   at Lithogen.Core.Implementations.ViewDirectoryProcessor.Execute() in c:\Users\pdaniels\repos\Lithogen\src\Lithogen.Core\Implementations\ViewDirectoryProcessor.cs:line 57
   at Lithogen.Core.Implementations.Builder.ExecuteViewsStep() in c:\Users\pdaniels\repos\Lithogen\src\Lithogen.Core\Implementations\Builder.cs:line 107
   at Lithogen.Core.Implementations.Builder.Build() in c:\Users\pdaniels\repos\Lithogen\src\Lithogen.Core\Implementations\Builder.cs:line 36
   at Lithogen.Program.Main(String[] args) in c:\Users\pdaniels\repos\Lithogen\src\Lithogen\Program.cs:line 46

**Comment by matthid** [comment] 2015-01-23 15:29
The problem is that while loading the template assembly the runtime cannot find Lithogen.Boilerplate.dll. I can only improve the exception message but not the root case (which lies in your setup).

**Comment by matthid** [comment] 2015-01-23 15:30
Hm, one could argue that RazorEngine should try to use the ReferenceResolver not only for compiling but also in this case, but I'm not sure of the side-effects..

**Comment by PhilipDaniels** [comment] 2015-01-23 15:42
Is it possible to get rid of the error by changing my code? I have tried loading Lithogen.Boilerplate.dll into the current AppDomain, but that still fails.

**Comment by PhilipDaniels** [comment] 2015-01-23 15:44
Or do you think it is related to the fact that Lithogen.Boilerplate.dll is outside of the normal assembly search path? That is, it is not in a folder underneath Lithogen.exe. Have had problems with that before in other projects.

**Comment by matthid** [comment] 2015-01-23 15:47
Yeah the problem is that the runtime can't find it by name, you have multiple ways of working around that:
- Drop the assemby side by side to Lithogen.exe
- Use the AssemblyUnresolved event
- Add search paths to app.config

And possibly more. But I'm still thinking about supporting this scenario natively in RazorEngine....

**Comment by matthid** [comment] 2015-01-23 17:33
Ok I decided to tackle this in RazorEngine because:
- It can lead to weird errors when the type is actually found (ie your secound RunCompile call), then the error will come up much later and it will be hard to debug
- In case of Isolation you do not want to setup your AppDomain with this stuff (it should just work)

The only problem I see is when people use ReferenceAssemblies I have no idea what will happen there, so I hope nobody does that...

You can use the branch https://github.com/Antaris/RazorEngine/tree/feature/load_template_references and check if that works for your (I need to let travis run before merging and releasing 3.5.2 with this).

**Comment by matthid** [comment] 2015-01-23 19:01
Fixed in 3.5.2.

**Closed by matthid** 2015-01-23 19:01 UTC
Labels: bug, Compilation

**Comment by PhilipDaniels** [comment] 2015-01-23 19:59
Fantastic! It's working now, that removes a blocking issue for me, thanks very much for the quick response. Nice to see the doc update too :+1:
