### ISSUE TITLE
Cannot debug template - when using @helper DoSmth(){}

### ISSUE THREAD

**Issue by martys** [Antaris/RazorEngine#253] opened 2015-03-23 17:44 UTC
Hi, 

While the RazorEngine parses and executes the @helper code correctly, 
I found myself un-able to debug the 'run-time' generated class after starting to use @helper 
functions in my Razord .cshtml templates 

basically - when I click F11 to step into the code, the debugger - jumps over it 
removing the @helper's- let's me step into the generated code and debug it . 

Is there any way around this ?

**Comment by matthid** [comment] 2015-03-24 01:24
I cannot reproduce this. I could even debug into a `@helper` function.
Did you set `Debug = true` and do you give RazorEngine the file path (via `new LoadedTemplateSource(template, templatePath)`)?

**Comment by martys** [comment] 2015-03-24 12:10
Yes, I did set the debug = true
and it allows me to step into the code if I don't user @helper

when I add a @helper to the razor view, #Resharper suggests that a system.web assembly should be added. and after that - the debugger just jumps over the .RunCompile() statement instead of stepping into it 

I should not I'm using this in the console app, not the MVC website

**Comment by martys** [comment] 2015-03-24 12:20
template path - no. I dont' specify. 
I read it from the database (in this sample it's a file) , add it and compile it up front
```cs
            var config = new TemplateServiceConfiguration();
            // .. configure your instance
            config.Debug = true;
            service = service ?? RazorEngineService.Create(config);
            if (service.IsTemplateCached(EmailBodyTemplateKey, typeof(ConflictCheckEmailModel))) return;
 
            service.AddTemplate(EmailBodyTemplateKey, File.ReadAllText(@".\EmailServices\Templates\ConflictCheckEmail.cshtml"));
            service.Compile(EmailBodyTemplateKey);
```
then run it in another method
```cs
            var stringWriter = new StringWriter();
            service.RunCompile(EmailBodyTemplateKey, stringWriter, model.GetType(), model);
           // Console.WriteLine("Elapsed : {0} miliseconds : {1}ms", sw.Elapsed, sw.ElapsedMilliseconds);
            Console.WriteLine(stringWriter.ToString());
```

**Comment by matthid** [comment] 2015-03-24 12:26
Try to use
```csharp
service.AddTemplate(EmailBodyTemplateKey, new LoadedTemplateSource(File.ReadAllText(@".\EmailServices\Templates\ConflictCheckEmail.cshtml", Path.GetFullPath (@".\EmailServices\Templates\ConflictCheckEmail.cshtml")));
```

But I will look into the generated C# code, maybe something is wrong. But `LoadedTemplateSource` is the supported way to debug into templates.

**Comment by matthid** [comment] 2015-03-24 13:06
Thanks for reporting this it will be fixed in the next version (ie work without specifying the template path).

**Comment by martys** [comment] 2015-03-24 17:09
When will it be possible to download it trough nuget ?

**Closed** 2015-03-24 18:00 UTC
Labels: bug

**Comment by matthid** [comment] 2015-03-24 18:24
Now released in https://www.nuget.org/packages/RazorEngine/3.6.3

**Comment by martys** [comment] 2015-03-24 19:04
Thank You

**Comment by shadyyehia** [comment] 2017-07-30 12:52
Hi, I face the same problem in version 3.10.0

my code is as following and I can't jump into the template file to debug, any advise please?

`  var config = new TemplateServiceConfiguration();
               
                config.Debug = true;
                config.EncodedStringFactory = new HtmlEncodedStringFactory(); // Html encoding.
                var service = RazorEngineService.Create(config);
                Engine.Razor = service;
                
                string template = GetTemplateContent(templateFilePath);
              
                var result = Engine.Razor.RunCompile(new LoadedTemplateSource(template, templateFilePath), new Random().Next().ToString(), null, jsonDataModel);`
