### ISSUE TITLE
Method not found: 'Void Microsoft.AspNet.Razor.CodeGenerators.GeneratedClassContext.set_ResolveUrlMethodName(System.String)'.

### ISSUE THREAD

**Issue by fenix2222** [Antaris/RazorEngine#351] opened 2016-01-05 06:35 UTC
I am getting the following exception when running latest 4.2.6-beta1 with Microsoft.AspNet.Razor 4.0.0-rc1-final:

Method not found: 'Void Microsoft.AspNet.Razor.CodeGenerators.GeneratedClassContext.set_ResolveUrlMethodName(System.String)'.

**Comment by matthid** [comment] 2016-01-20 17:38
Duplicate of https://github.com/Antaris/RazorEngine/issues/322

**Closed by matthid** 2016-01-20 17:38 UTC
