### ISSUE TITLE
Serialization problem

### ISSUE THREAD

**Issue by imperugo** [Antaris/RazorEngine#267] opened 2015-04-10 12:10 UTC
Hi folks, 
I'm getting an error during ```RunCompile```method.

For a reason that I don't know the lasted version or RazorEngine is trying to serialize a class used into my project. That class is not serializable for tha reason the app crashes.
The weird part is that the previous version of RazorEngine was working, so probably is something related to the new version.

Here the error message:

```
Type 'Owin.OwinRequestScopeContext' in assembly 'OwinRequestScopeContext, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
```

and here the stack

```
at System.AppDomain.InternalCreateInstanceFromWithNoSecurity(String assemblyName, String typeName) at RazorEngine.Compilation.CrossAppDomainCleanUp..ctor(AppDomain toWatch, IPrinter printer) at RazorEngine.Compilation.CrossAppDomainCleanUp.CreateInitial() at System.Lazy`1.CreateValue() --- End of stack trace from previous location where exception was thrown --- at System.Lazy`1.get_Value() at RazorEngine.Compilation.CrossAppDomainCleanUp.RegisterCleanup(String item, Boolean throwOnDefault) at RazorEngine.Templating.DefaultCachingProvider.CacheTemplate(ICompiledTemplate template, ITemplateKey templateKey) at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType) at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss) at RazorEngine.Templating.RazorEngineService.GetTemplate(ITemplateKey key, Type modelType, Object model, DynamicViewBag viewbag) at RazorEngine.Templating.TemplateService.GetTemplate(String razorTemplate, Object model, String cacheName) at RazorEngine.Templating.TemplateService.Parse(String razorTemplate, Object model, DynamicViewBag viewBag, String cacheName) at RazorEngine.Razor.Parse[T](String razorTemplate, T model, String cacheName) at 
```

Any hint?

**Comment by matthid** [comment] 2015-04-10 12:51
Can you tell me more about your environment? This has to do with the cleanup code, which ensures that temporary files are deleted once the AppDomain has been unloaded.

If you are fine with temporary files remaining on disk you can use:

```csharp
config.CachingProvider = new DefaultCachingProvider(t => { 
    /*TODO: Delete t after the application has been closed */ })
```

But this needs further investigation why it wants to serialize your class...

**Comment by matthid** [comment] 2015-04-10 13:05
Can you try to spin up a new `Thread` dedicated for RazorEngine only and see if that fixes the problem?

**Comment by imperugo** [comment] 2015-04-10 13:54
Hi @matthid 
your fix works!!!
About the environment I'm on Windows 8.1, IIS, MVC/WebApi/Owin latest version and I'm using RazorEngine into [IdentityServer3](https://github.com/IdentityServer/IdentityServer3).

All packages are up to date from nuget.
Do you need more info?

**Comment by matthid** [comment] 2015-04-10 14:14
Well it's not really a fix as you now need to cleanup your temp files regularly ...
I think I now know what the issue is (even I have no repro). The info provided in #268 helped. Thanks @impworks.

Can you test the `Thread` method as well (ie just wrapping RazorEngine calls to a new Thread) 
and if it doesn't work:

```csharp
using (var flow = System.Threading.ExecutionContext.SuppressFlow()) {
  // Call RazorEngine here
  flow.Undo()
}
```

And if that doesn't work a combination of those (spin up a new thread while the flow is suppressed).

If that works I can integrate a fix in RazorEngine.

**Comment by imperugo** [comment] 2015-04-10 14:22
Doing this

```csharp
using (var flow = System.Threading.ExecutionContext.SuppressFlow()) 
{
	parsedHtml = Engine.Razor.RunCompile(template, cacheKey, model.GetType(), model);
	
	// Call RazorEngine here
	flow.Undo();
}
```

I still have the error.

**Comment by imperugo** [comment] 2015-04-10 14:24
btw I'm on async method, so another thread, maybe could be useful to know

**Comment by matthid** [comment] 2015-04-10 14:29
And with
```csharp
using (var flow = System.Threading.ExecutionContext.SuppressFlow()) 
{
    var t = new System.Threading.Thread(() =>
    {
          parsedHtml = Engine.Razor.RunCompile(template, cacheKey, model.GetType(), model);
    });
    t.Start();
    t.Join();
    flow.Undo();
}
```
?

**Comment by imperugo** [comment] 2015-04-10 14:31
In this case parsedHtml is not available out or that thread. I should wait right?

**Comment by matthid** [comment] 2015-04-10 14:35
yeah wait for the thread to finish. It's just for testing I don't recommend using this code ...

**Comment by imperugo** [comment] 2015-04-10 14:56
I'm getting ```AsyncFlowControl object can be used only once to call Undo().```

with that
```csharp
using (var flow = System.Threading.ExecutionContext.SuppressFlow())
{
	var t = new System.Threading.Thread(() =>
	{
		parsedHtml = Engine.Razor.RunCompile(template, cacheKey, model.GetType(), model);
	});
	t.Start();
	t.Join();
	flow.Undo();

	return Task.FromResult(StringToStream(parsedHtml));
}
```

**Comment by matthid** [comment] 2015-04-10 15:07
I think you can remove the `Undo` call. But it removes the other Exception which looks good.

**Comment by imperugo** [comment] 2015-04-10 15:17
Ok works.
So what's the best workaround? New thread or Caching Provider?

**Comment by matthid** [comment] 2015-04-10 15:29
Thanks for testing this! Now that I know this is fixable I will try to provide a fixed version of RazorEngine as nuget beta package (for testing the fix). In the meantime you can use my initial workaround (just make sure to manually delete all temp files once I released the fixed version).

**Comment by imperugo** [comment] 2015-04-10 15:31
Ok Thanks,
are you using the ASP.NET Temporary Folder?
In this case could be a problem because I'm using it on an Azure Cloud service

**Comment by matthid** [comment] 2015-04-10 17:15
Can you try if https://www.nuget.org/packages/RazorEngine/3.6.5-beta1 fixes the problem (and has no other problems in your scenario)?

**Comment by matthid** [comment] 2015-04-11 18:57
Released in 3.6.5

**Comment by imperugo** [comment] 2015-04-13 08:22
Just installed the 3.6.5 and the problem still here with a different "format".

```
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at RazorEngine.Compilation.CrossAppDomainCleanUp.CallHelperSafe[T](Func`1 a) at RazorEngine.Compilation.CrossAppDomainCleanUp..ctor(AppDomain toWatch, IPrinter printer) at RazorEngine.Compilation.CrossAppDomainCleanUp.CreateInitial() at System.Lazy`1.CreateValue() --- End of stack trace from previous location where exception was thrown --- at System.Lazy`1.get_Value() at RazorEngine.Compilation.CrossAppDomainCleanUp.RegisterCleanup(String item, Boolean throwOnDefault) at RazorEngine.Templating.DefaultCachingProvider.CacheTemplate(ICompiledTemplate template, ITemplateKey templateKey) at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType) at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss) at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag) at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer) at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter) 
```

Now I've a inner exception that is saying almost the same thing:

```
Type 'Owin.OwinRequestScopeContext' in assembly 'OwinRequestScopeContext, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
```

and the stack of the inner is:

```
at System.AppDomain.InternalCreateInstanceFromWithNoSecurity(String assemblyName, String typeName) at RazorEngine.Compilation.CrossAppDomainCleanUp.InitHelper.CreateHelper() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute()
```

Should I change my code with that release?

**Comment by matthid** [comment] 2015-04-13 08:41
Wait,... what?
So the above code worked, and:

```csharp
using (var flow = System.Threading.ExecutionContext.SuppressFlow())
{
    parsedHtml = Task.Run(() =>
    {
        return Engine.Razor.RunCompile(template, cacheKey, model.GetType(), model);
    }).Result;
    return Task.FromResult(StringToStream(parsedHtml));
}
```
does not work?

**Comment by imperugo** [comment] 2015-04-13 08:47
No, 
that's the message:

```Context flow is already suppressed.```

Stack
```
at System.Threading.ExecutionContext.SuppressFlow() at RazorEngine.Compilation.CrossAppDomainCleanUp.CallHelperSafe[T](Func`1 a) at RazorEngine.Compilation.CrossAppDomainCleanUp..ctor(AppDomain toWatch, IPrinter printer) at RazorEngine.Compilation.CrossAppDomainCleanUp.CreateInitial() at System.Lazy`1.CreateValue() --- End of stack trace from previous location where exception was thrown --- at System.Lazy`1.get_Value() at RazorEngine.Compilation.CrossAppDomainCleanUp.RegisterCleanup(String item, Boolean throwOnDefault) at RazorEngine.Templating.DefaultCachingProvider.CacheTemplate(ICompiledTemplate template, ITemplateKey templateKey) at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType) at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss) at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag) at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer) at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter) 
```

**Comment by matthid** [comment] 2015-04-13 08:47
I'm a bit puzzled because I managed to reproduce the initial exception, added a unit test and fixed it. Now the question is why that solution doesn't work in your environment.

**Comment by matthid** [comment] 2015-04-13 08:49
Ok I guess you should try:
```csharp
using (var flow = System.Threading.ExecutionContext.SuppressFlow())
{
    parsedHtml = Task.Run(() =>
    {
        System.Threading.ExecutionContext.RestoreFlow();
        return Engine.Razor.RunCompile(template, cacheKey, model.GetType(), model);
    }).Result;
    return Task.FromResult(StringToStream(parsedHtml));
}
```

**Comment by imperugo** [comment] 2015-04-13 08:51
nope :(

Cannot restore context flow when it is not suppressed.

**Comment by matthid** [comment] 2015-04-13 08:58
can you try my initial code with the previous version 3.6.4?

**Comment by matthid** [comment] 2015-04-13 09:16
Well nevermind, I will just release a version that uses threads, I figured using Tasks would be a bit less of an overhead (and it worked in my testing)...

**Comment by imperugo** [comment] 2015-04-13 09:24
Ok, let me know when u release it

**Comment by matthid** [comment] 2015-04-13 13:01
Does it work with https://www.nuget.org/packages/RazorEngine/3.6.6-beta1 ?

**Comment by matthid** [comment] 2015-04-13 13:41
And if it does it hopefully works with https://www.nuget.org/packages/RazorEngine/3.6.6-beta2 as well. Because I can't really release beta1 as it spins up a lot of threads internally....

**Comment by matthid** [comment] 2015-04-16 09:14
@imperugo Do those beta releases work for you? The problem is that this time I couldn't reproduce your issue within a unit test.

**Comment by timkly** [comment] 2015-04-22 06:24
I'm having a similar issue on the rackspace cloud - upgrading to latest beta looks to have resolved but the issue for me at least was here

Type is not resolved for member 'RazorEngine.Compilation.CrossAppDomainCleanUp+ErrorOnlyPrinter,RazorEngine, Version=3.6.5.0, Culture=neutral, PublicKeyToken=9ee697374c7e744a'.<br/>   at RazorEngine.Compilation.CrossAppDomainCleanUp.CleanupHelper.Init(AppDomain domain, IPrinter printer)
   at RazorEngine.Compilation.CrossAppDomainCleanUp.InitHelper.CreateHelper()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by matthid** [comment] 2015-04-22 10:51
@timkly So the `beta2` works without problems?

**Closed** 2015-04-22 19:19 UTC
Labels: bug

**Comment by matthid** [comment] 2015-04-22 20:24
Released with https://www.nuget.org/packages/RazorEngine/3.6.6 so hopefully this works in all cases now.

**Comment by timkly** [comment] 2015-04-24 09:12
Sorry Matt. That did fix it. Great work

**Comment by MarcelChirtes** [comment] 2018-12-04 20:10
Updated lately some projects in a solution in from 4.5 and 4.5.1 to 4.6, project where razor build problem reported here reappeared, the original suggested fix works:

```
                var config = new RazorEngine.Configuration.TemplateServiceConfiguration
                {
                    CachingProvider = new DefaultCachingProvider(t => { })
                };
                Engine.Razor = RazorEngineService.Create(config);
                //...                
```
